### ISSUE TITLE
Found error log when click edit proxy host

### ISSUE THREAD

**Issue by rokoman** [ZoeyVid/NPMplus#410] opened 2023-09-25 20:40 UTC
![e1](https://github.com/ZoeyVid/nginx-proxy-manager/assets/1106739/fb877690-c218-46da-a854-104a17d111e8)

[Access   ] › ✖  error     access_lists:list undefined validation failed

**Comment by Zoey2936** [comment] 2023-09-25 20:43
can I see the config of the access list?

**Comment by rokoman** [comment] 2023-09-25 20:45
> can I see the config of the access list?

I don't config access list. but i test on other user no view access list.

**Comment by Zoey2936** [comment] 2023-09-25 20:46
I don't understand

**Comment by rokoman** [comment] 2023-09-25 20:52
![user1](https://github.com/ZoeyVid/nginx-proxy-manager/assets/1106739/a894443e-d810-4c36-957a-d64bd39bb6b3)

I add new user and set permission hidden access list, when edit proxy host i found error log (access_lists:list undefined validation failed).

On admin user no error log when edit proxy host.

**Comment by Zoey2936** [comment] 2023-11-09 17:40
I can confirm it, but beside the log everything works

**Comment by Zoey2936** [comment] 2023-11-09 17:41
so I would close it, since it is only a misleading log and no issue from my view

**Closed as completed** 2023-11-11 18:07 UTC
